import polib

po = polib.pofile('translations/uz/LC_MESSAGES/messages.po')

translations = {
    "AI CV Analyzer": "SI Rezyume Tahlilchisi",
    "Dashboard": "Boshqaruv Paneli",
    "Upload CV": "Rezyume Yuklash",
    "Logout": "Chiqish",
    "Get Started": "Boshlash",
    "Welcome,": "Xush kelibsiz,",
    "Manage and view your CV analysis history.": "Rezyume tahlil tarixini boshqaring va ko'ring.",
    "Upload New CV": "Yangi Rezyume Yuklash",
    "Your Uploaded CVs": "Yuklangan Rezyumelar",
    "File": "Fayl",
    "Upload Date": "Yuklangan Sana",
    "Overall Score": "Umumiy Ball",
    "Action": "Amal",
    "Pending": "Kutilmoqda",
    "View Results": "Natijalarni Ko'rish",
    "No CVs found": "Rezyume topilmadi",
    "Upload your first CV to get AI-powered feedback.": "SI yordamida fikr-mulohaza olish uchun birinchi rezyumengizni yuklang.",
    "Upload Now": "Hozir Yuklash",
    "Welcome Back": "Xush kelibsiz",
    "Please login to your account": "Iltimos, hisobingizga kiring",
    "Email address": "Elektron pochta",
    "Password": "Parol",
    "Remember me": "Meni eslab qol",
    "Don't have an account?": "Hisobingiz yo'qmi?",
    "Register here": "Shu yerda ro'yxatdan o'ting",
    "Create an Account": "Hisob Yaratish",
    "Join us to get your CV analyzed": "Rezyumengizni tahlil qilish uchun bizga qo'shiling",
    "First Name": "Ism",
    "Last Name": "Familiya",
    "Sign Up": "Ro'yxatdan O'tish",
    "Already have an account?": "Allaqachon hisobingiz bormi?",
    "Login here": "Shu yerda kiring",
    "Analysis Results": "Tahlil Natijalari",
    "For": "Uchun",
    "Back to Dashboard": "Boshqaruv Paneliga Qaytish",
    "Excellent CV! Just a few minor tweaks needed.": "Ajoyib rezyume! Faqat bir nechta kichik o'zgarishlar kerak.",
    "Good start, but needs significant improvements.": "Yaxshi boshlanish, ammo jiddiy yaxshilanishlarni talab qiladi.",
    "Needs a major rewrite to be competitive.": "Raqobatbardosh bo'lish uchun to'liq qayta yozish kerak.",
    "Score Breakdown": "Ballar Taqsimoti",
    "Structure & Flow": "Tuzilma va Oqim",
    "Skills Match": "Ko'nikmalar Mosligi",
    "Formatting": "Formatlash",
    "Content & Clarity": "Tarkib va Aniqlik",
    "AI-Generated Feedback": "SI Tomonidan Yaratilgan Fikr-mulohaza",
    "General Overview": "Umumiy Ko'rinish",
    "Actionable Suggestions": "Amaliy Takliflar",
    "Upload Your CV": "Rezyumengizni Yuklang",
    "Supported formats": "Qo'llab-quvvatlanadigan formatlar",
    "Click or drag file to this area to upload": "Yuklash uchun faylni bosing yoki shu maydonga torting",
    "Maximum file size": "Maksimal fayl hajmi",
    "Analyze CV": "Rezyumeni Tahlil Qilish",
    "Analyzing your CV...": "Rezyumengiz tahlil qilinmoqda...",
    "Our AI is reading your document and generating feedback.": "Bizning SI hujjatingizni o'qib chiqmoqda va fikr-mulohaza yaratmoqda.",
    "Your CV has a good overall structure but lacks specific metrics in the experience section.": "Rezyumengiz tuzilishi yaxshi, biroq tajriba bo'limida aniq ko'rsatkichlar yetishmaydi.",
    "- Add quantifiable achievements to your work experience.\n- Highlight technical skills more prominently.\n- Improve formatting consistency.": "- Ish tajribangizga miqdoriy yutuqlarni qo'shing.\n- Texnik ko'nikmalarni ko'proq ajratib ko'rsating.\n- Formatlash izchilligini yaxshilang.",
    "Your CV has an excellent structure that makes it easy to read.": "Rezyumengiz ajoyib tuzilishga ega, uni o'qish juda oson.",
    "The structure of your CV is good, but could be organized slightly better.": "Rezyumengizning tuzilishi yaxshi, biroq biroz yaxshiroq tashkil etilishi mumkin.",
    "- Consider moving your most relevant experience closer to the top.": "- Eng tegishli tajribangizni yuqoriroqqa ko'chirishni ko'rib chiqing.",
    "The CV structure is somewhat confusing and may be hard for recruiters to scan.": "Rezyume tuzilishi biroz chalkash va ish beruvchilar ko'zdan kechirishi uchun qiyin bo'lishi mumkin.",
    "- Use clear headings (Experience, Education, Skills).": "- Aniq sarlavhalardan foydalaning (Tajriba, Ta'lim, Ko'nikmalar).",
    "- Ensure chronological order is used correctly.": "- Xronologik tartibdan to'g'ri foydalanilganiga ishonch hosil qiling.",
    "You have a strong, well-defined skills section.": "Sizda kuchli, yaxshi ta'riflangan ko'nikmalar bo'limi bor.",
    "Your skills section is decent, but could be more targeted.": "Sizning ko'nikmalar bo'limingiz yaxshi, biroq ko'proq maqsadli bo'lishi mumkin.",
    "- Add more specific technical keywords related to your industry.": "- Sanoatingizga tegishli aniqroq texnik kalit so'zlarni qo'shing.",
    "The skills section is lacking depth and might not pass Applicant Tracking Systems (ATS).": "Ko'nikmalar bo'limida chuqurlik yetishmaydi va Nomzodlarni Kuzatish Tizimlaridan (ATS) o'ta olmasligi mumkin.",
    "- Create a dedicated 'Skills' section.": "- Maxsus 'Ko'nikmalar' bo'limini yarating.",
    "- List both hard and soft skills clearly.": "- Qattiq va yumshoq ko'nikmalarni aniq sanab o'ting.",
    "Your descriptions are impactful and action-oriented.": "Tavsiflaringiz ta'sirli va harakatga yo'naltirilgan.",
    "Your experience descriptions are okay, but lack measurable impact.": "Tajriba tavsiflaringiz yaxshi, ammo o'lchanadigan ta'sirga ega emas.",
    "- Add quantifiable achievements (e.g., 'Increased sales by 20%').": "- Miqdoriy yutuqlarni qo'shing (masalan, 'Sotuvlarni 20% ga oshirdi').",
    "The content focuses too much on daily duties rather than achievements.": "Tarkib yutuqlardan ko'ra ko'proq kundalik vazifalarga qaratilgan.",
    "- Focus on what you accomplished, not just what you were assigned to do.": "- Faqat sizga yuklatilgan vazifalarga emas, balki erishgan natijalaringizga e'tibor qarating.",
    "Recommended Job Positions:": "Tavsiya Etilgan Ish O'rinlari:"
}

for entry in po:
    if entry.msgid in translations:
        entry.msgstr = translations[entry.msgid]

po.save()
print("Translations updated!")
